config/routes.rb
Rails.application.routes.draw do

  resources :items
  resources :item_histories

  get '/download_stock_report' => 'items#download_stock_report'

  root 'items#index'

end

app/models/item.rb
class Item < ActiveRecord::Base
  has_one :item_history, dependent: :destroy
end

app/models/item_history.rb
class ItemHistory < ActiveRecord::Base

  belongs_to :item
  has_many :item_history_periods, dependent: :destroy
  accepts_nested_attributes_for :item_history_periods, reject_if: :all_blank, allow_destroy: true

end

app/models/item_history_period.rb
class ItemHistoryPeriod < ActiveRecord::Base
  belongs_to :item_history
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include ItemsHelper
  include ItemHistoriesHelper

  def respond_modal_with(*args, &blk)
    options = args.extract_options!
    options[:responder] = ModalResponder
    respond_with *args, options, &blk
  end

end

app/controllers/item_histories_controller.rb
class ItemHistoriesController < ApplicationController

  respond_to :html, :js
  before_action :set_item_history, only: [:demand_update, :show, :update]
  before_action :demand_update, only: [:show]
  before_action :modal_responder, only: [:show]

  include Math
  require 'descriptive_statistics'

  def show
  end

  def update
    @item_history.update_attributes(item_history_params)

    # Atualiza a demanda total do item
    actual_total_demand = view_context.get_total_demand(@item_history)
    @item_history.item.update_attribute(:demand, actual_total_demand)

    # Atualiza o estoque mínimo do item
    demand_standard_deviation = demand_array(@item_history).standard_deviation
    security_factor = 1.645
    lead_time = 2.0
    minimum_stock = security_factor * demand_standard_deviation * Math.sqrt(lead_time)

    @item_history.item.update_attribute(:minimum_stock, minimum_stock)
    
    respond_to do |format|
      format.html { redirect_to items_path, notice: 'O histórico do item foi atualizado!' }
    end
  end

  private

  def set_item_history
    @item_history = ItemHistory.find(params[:id])
  end

  # Esse método atualiza as demandas totais e média, mas 
  # somente quando as demandas anteriores forem diferentes
  def demand_update

    previous_total_demand = @item_history.total
    actual_total_demand = view_context.get_total_demand(@item_history)
    media_demand = view_context.get_media_demand(@item_history)

    unless previous_total_demand == actual_total_demand
      @item_history.update_attribute(:total, actual_total_demand)
      @item_history.update_attribute(:media, media_demand)
    end

  end

  def modal_responder
    respond_modal_with set_item_history
  end

  def item_history_params
    params.require(:item_history).permit(item_history_periods_attributes: [:id, :period, :demand, :_destroy])
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  respond_to :html, :js
  before_action :modal_responder, only: [:edit]
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all.order(:code).includes(:item_history)
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end
  
  # GET /download_stock_report
  def download_stock_report
    send_file generate_report
  end

  # GET /items/new
  def new
    respond_modal_with @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        # Cria histórico para o item
        ItemHistory.create(item_id: @item.id, media: 0, total: 0)

        format.html { redirect_to items_path, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to items_path, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    def modal_responder
      respond_modal_with set_item
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:code, :description, :units)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/item_histories_helper.rb
module ItemHistoriesHelper

  include Math
  require 'descriptive_statistics'

  def demand_array(item_history)
    array = []

    item_history.item_history_periods.each do |ihp|
      array << ihp.demand
    end

    array
  end

  def get_total_demand(item_history)
    demand_array(item_history).sum
  end

  def get_media_demand(item_history)
    demand_array(item_history).mean
  end

  # def get_minimum_stock(item_history)
  #   demand_standard_deviation = demand_array(item_history).standard_deviation
  #   security_factor = 1.645
  #   lead_time = 2.0
  #   mininum_stock = security_factor * demand_standard_deviation * Math.sqrt(lead_time)
  # end

end

app/helpers/items_helper.rb
module ItemsHelper

  def generate_report

    items = Item.all.includes(:item_history)

    Prawn::Document.generate(Rails.root.join('tmp').to_s + '/relatorio_de_estoque.pdf') do

      y_position = cursor - 10

      bounding_box([0, y_position], width: 200, height: 75) do
       text "Necessidades Urgentes S.A.", leading: 6, style: :bold
       text "Sistema de Controle de Estoque"
      end

      bounding_box([340, y_position], width: 200, height: 75) do
       text "Relatório de Situação de Estoque", leading: 6, style: :bold, align: :right
       data = Time.now.strftime("em %d/%m/%Y às %H:%Mh")
       text data, align: :right
      end

      data = [["Código  ", "Descrição", "Unidades\nExistentes", "Demanda\nTotal", "Demanda\nMédia", "Estoque Mínimo", "Renovação?"]]
      
      items.each do |item|

        if item.units < item.minimum_stock
          renovacao = "Sim"
        else
          renovacao = "Não"
        end

        data += [[item.code.to_s, item.description, item.units.to_s, 
                  item.demand.to_s, item.item_history.media.to_s,
                  item.minimum_stock.to_s, renovacao]]
      end

      table(data, header: true, row_colors: ["F0F0F0", "FFFFFF"], cell_style: { size: 10 })
    end

    Rails.root.join('tmp').to_s + '/relatorio_de_estoque.pdf'

  end

end

app/views/item_histories/_item_history_period_fields.html.slim
.nested-fields
  
  .row

    .col-sm-5.col-xs-5
      = f.label 'Período'
      = f.number_field :period, class:'form-control input-sm', min: 1, required: true
    
    .col-sm-6.col-xs-6
      = f.label 'Demanda'
      = f.number_field :demand, class:'form-control input-sm', min: 0, required: true
    
    .col-sm-1.col-xs-1 style="padding-top: 30px"
      = link_to_remove_association f do
        i.fa.fa-times

  hr.divider

app/views/item_histories/show.html.slim
= content_for :title, 'Histórico do item: ' + @item_history.item.description

.modal-body

  - if @item_history.item_history_periods.blank?

    .alert.alert-info
      button.close[type="button" data-dismiss="alert" aria-label="Close"]
        span[aria-hidden="true"]
        | ×
      | Não há lançamentos para este item.

  - else

    .alert.alert-info
      .row
        .col-sm-6.col-xs-12
          | Demanda total: 
          = @item_history.total
          |  unidades.
        .col-sm-6.col-xs-12
          | Demanda média: 
          = @item_history.media
          |  unidades.

  = form_for @item_history do |f|

    #item_history_periods
      = f.fields_for :item_history_periods do |item_history_period|
        = render 'item_history_period_fields', f: item_history_period
      .links
        = link_to_add_association 'Adicionar Período/Demanda', f, :item_history_periods, class:'btn btn-default btn-sm'
    
    = f.submit 'Atualizar Histórico', class:'btn btn-success pull-right'

.modal-footer

app/views/items/_form.html.slim
.modal-body

  = form_for @item do |f|

    .form-group
      = f.label 'Código'
      = f.number_field :code, class:'form-control', min: 0, required: true

    .form-group
      = f.label 'Descrição'
      = f.text_field :description, class:'form-control', required: true

    .form-group
      = f.label 'Unidades'
      = f.number_field :units, class:'form-control', min: 0, required: true

    - if current_page?(new_item_path)
      = f.submit 'Criar item', class:'btn btn-success pull-right'
    - else
      = f.submit 'Atualizar item', class:'btn btn-success pull-right'

.modal-footer

app/views/items/edit.html.slim
= content_for :title, 'Atualizar Item de Estoque'

== render 'form'

app/views/items/index.html.slim
- if @items.blank?
  
  .alert.alert-danger
    | Não há itens em estoque.

  = link_to 'Novo Item', new_item_path, data: { modal: true }, class:'btn btn-primary'
  
- else

  table#estoque.table.table-striped.table-responsive.table-bordered

    thead

      tr
        th Código
        th Descrição
        th Unidades existentes
        th Demanda total
        th.text-right Histórico
        th
        th

    tbody

      - @items.each do |item|

        tr
          td = item.code
          td = item.description
          td = item.units
          td
            - if item.demand.nil?
              | 0 unidades
            - else
              = item.demand
              |  unidades
              
          td align='right'
            = link_to item.item_history, data: { modal: true }, title:'Ver Histórico' do
              i.fa.fa-eye

          td align='right'
            = link_to edit_item_path(item), title: 'Editar', data: { modal: true } do
              i.fa.fa-pencil

          td align='right'
            = link_to item, data: { confirm: 'Excluir item?' }, method: :delete, title: 'Excluir' do
              i.fa.fa-times

  br

  .btn-group.btn-group-sm
    = link_to 'Novo Item', new_item_path, data: { modal: true }, class:'btn btn-primary'
    = link_to 'Gerar Relatório de Estoque', download_stock_report_path, class:'btn btn-primary'

javascript:
  $(document).ready(function() {
      $('#estoque').DataTable( {
        "iDisplayLength": 8,
        columnDefs: [ { orderable: false, targets: [5, 6] } ],
        "language": {
            "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Portuguese.json"
        }
      } );
  } );

app/views/items/new.html.slim
= content_for :title, 'Novo Item de Estoque'

== render 'form'

app/views/items/show.html.slim
p#notice = notice

p
  strong Code:
  = @item.code
p
  strong Description:
  = @item.description
p
  strong Units:
  = @item.units
p
  strong Demand:
  = @item.demand

= link_to 'Edit', edit_item_path(@item)
'|
= link_to 'Back', items_path

app/views/layouts/_about_modal.html.slim
p.text-justify
  | O Sistema de Controle de Estoque é um sistema de informações gerenciais da empresa NecessidadesUrgentes S.A. desenvolvido pela empresa SoluçõesSoftwares LTDA.

p.text-justify
  | O módulo de cálculo de estoque mínimo e exportação de relatório de situação de estoque tem como entrada os itens cadastrados no estoque (arquivo-mestre) e como saída o estoque mínimo e um relatório em formato para impressão.

hr.divider

img src="http://i.imgur.com/vQ9gUC9.png" align="middle"

hr.divider

p.text-justify
  | O cálculo do estoque mínimo é calculado tendo como base o histórico de pedidos de cada item, um fator de segurança e um 
  em lead time
  |  (tempo de entrega)

hr.divider

p.text-justify
  | Este é o primeiro trabalho da disciplina de Sistemas de Informação - Turma A, da Universidade de Brasília no 1º semestre de 2016.

p.text-justify
  | Esse sistema foi desenvolvido por Rafael Alves Fernandes, matrícula 14/0030395.

p.text-justify
  | Esse sistema utiliza 
  em Ruby
  |  como linguagem de programação, 
  em Ruby on Rails 
  |  como framework WEB baseado em MVC, 
  em PostgreSQL 
  |  como gerenciador de banco de dados, 
  em HTML, SCSS e Javascript 
  | como linguagens de marcação, estilo e script no 
  em frontend, 
  |  além de 
  em Bootstrap e Bootswatch 
  | como framework CSS.

app/views/layouts/application.html.slim
doctype html

html

  head
    title
      | SCE
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css"
    link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/t/bs/dt-1.10.11/datatables.min.css"
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    script type="text/javascript" src="https://cdn.datatables.net/t/bs/dt-1.10.11/datatables.min.js"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    = csrf_meta_tags

  body.container

    #modal-holder
    
    nav.navbar.navbar-default.navbar-center.navbar-fixed-top
      
      .container
        
        .navbar-brand
          | Sistema de Controle de Estoque
      
        button type="button" class="btn btn-default navbar-btn pull-right" data-toggle="modal" data-target="#about-modal"
          | Sobre

        p.navbar-text.pull-right
          | Desenvolvido por Rafael Alves Fernandes

    - unless flash.notice.nil?
      #flash.alert.alert-info
        button.close[type="button" data-dismiss="alert" aria-label="Close"]
          span[aria-hidden="true"]
          | ×      
        = notice
  
    = yield

    .modal#about-modal.fade[tabindex="-1" role="dialog"]
      .modal-dialog
        .modal-content
          .modal-header
            button.close[type="button" data-dismiss="modal" aria-label="Close"]
              span[aria-hidden="true"]
                | ×
            h4.modal-title
              | Sobre
          .modal-body
            = render 'layouts/about_modal'
          .modal-footer
            button.btn.btn-primary[type="button" data-dismiss="modal"]
              | Ok

app/views/layouts/modal.html.slim
#mainModal.modal.custom.fade aria-hidden="true" aria-labelledby="mainModalLabel" role="dialog" tabindex="-1" 
  .modal-dialog
    .modal-content
      .modal-header
        button.close data-dismiss="modal" type="button" 
          span aria-hidden="true"  ×
          span.sr-only Fechar
        h4#mainModalLabel.modal-title
          = yield :title if content_for? :title
      = yield